version: '3'

services:

  # Code
  sls:
    ports: [ "3000:3000" ]
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - WEBHOOK_URL
      - SIGNING_SECRET
      - SLS_DEBUG
    command: npx sls offline --host 0.0.0.0 --printOutput
    volumes:
      - "node_modules:/app/node_modules"
      - ".:/app:cached"
    tty: true
    stdin_open: true

volumes:
  node_modules:
