FROM python:3.7-slim

RUN set -x \
  && apt-get update -qq \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y \
        nodejs npm \
  && apt-get clean -y

RUN npm install -g serverless@1.51.0
RUN pip install pipenv

COPY Pipfile Pipfile.lock ./
RUN pipenv install --deploy --system --dev

ENTRYPOINT ["serverless"]
